import {FirestoreService} from "./database/firestore.service";
import {StorageService} from "./storage/storage.service";
import {COLLECTIONS} from "../config/constants";
import {logger} from "../utils/logger.util";
import {createNotFoundError} from "../utils/error.util";
import sharp from "sharp";
import ffmpeg from "fluent-ffmpeg";
import {v4 as uuidv4} from "uuid";
import fs from "fs/promises";
import path from "path";

export interface MemoryInput {
  title?: string | null;
  description?: string | null;
  tags?: string[];
  visibility?: "private" | "guests" | "public";
  createdBy?: string | null;
}

interface FileInfo {
  buffer: Buffer;
  mimetype: string;
  fileName: string;
  originalName: string;
  size: number;
  mediaType: "image" | "video" | "other";
}

export class MemoriesService {
  static async listMemories(eventId: string): Promise<any[]> {
    return FirestoreService.getSubcollection(COLLECTIONS.EVENTS, eventId, COLLECTIONS.MEMORIES);
  }

  static async getMemory(eventId: string, memoryId: string): Promise<any> {
    const memory = await FirestoreService.getSubcollectionDocument(
      COLLECTIONS.EVENTS,
      eventId,
      COLLECTIONS.MEMORIES,
      memoryId
    );

    if (!memory) {
      throw createNotFoundError("Memory");
    }

    return memory;
  }

  static async getMediaById(mediaId: string): Promise<any> {
    return FirestoreService.getDocument(COLLECTIONS.MEDIA, mediaId);
  }

  static async getDownloadUrl(mediaId: string): Promise<string> {
    const media = await this.getMediaById(mediaId);
    if (!media) throw createNotFoundError("Media");
    if (!media.storagePath) throw new Error("Media storagePath missing");
    return StorageService.generateSignedUrl(media.storagePath, 3600);
  }

  static async createMemory(eventId: string, data: MemoryInput): Promise<any> {
    const createdAt = new Date().toISOString();
    const memory = await FirestoreService.createSubcollectionDocument(
      COLLECTIONS.EVENTS,
      eventId,
      COLLECTIONS.MEMORIES,
      {
        eventId,
        uploaderId: data.createdBy || null,
        mediaUrl: null,
        storagePath: null,
        mediaType: "note",
        thumbnailUrl: null,
        caption: data.title || data.description || null,
        tags: data.tags || [],
        visibility: data.visibility || "guests",
        uploadedAt: createdAt,
        updatedAt: createdAt,
        size: 0,
        contentType: null,
        mediaId: null,
      }
    );

    logger.info("Memory (note) created", {eventId, memoryId: memory.id});
    return memory;
  }

  static async uploadMemory(eventId: string, data: MemoryInput, fileInfo?: FileInfo): Promise<any> {
    // If no file provided => fallback to createMemory (note)
    if (!fileInfo) {
      return this.createMemory(eventId, data);
    }

    // Upload original file to Storage
    const storagePath = fileInfo.fileName; // already generated by middleware
    await StorageService.uploadBuffer(storagePath, fileInfo.buffer, fileInfo.mimetype);

    // Generate thumbnail
    let thumbnailPath: string | null = null;
    let thumbnailUrl: string | null = null;

    try {
      if (fileInfo.mediaType === "image") {
        const thumbBuffer = await sharp(fileInfo.buffer)
          .rotate()
          .resize(640, null, {withoutEnlargement: true})
          .jpeg({quality: 75})
          .toBuffer();

        const thumbName = storagePath.replace(/(\.\w+)$/, "-thumb.jpg");
        await StorageService.uploadBuffer(thumbName, thumbBuffer, "image/jpeg");
        thumbnailPath = thumbName;
        thumbnailUrl = await StorageService.generateSignedUrl(thumbName, 3600);
      } else if (fileInfo.mediaType === "video") {
        // Write buffer to tmp file for ffmpeg to consume
        try {
          const tmpDir = "/tmp";
          const tmpFile = path.join(tmpDir, `${uuidv4()}.mp4`);
          await fs.writeFile(tmpFile, fileInfo.buffer);
          const snapshotFile = path.join(tmpDir, `${uuidv4()}.jpg`);

          await new Promise<void>((resolve, reject) => {
            ffmpeg(tmpFile)
              .screenshots({
                timestamps: ["0.5"],
                filename: path.basename(snapshotFile),
                folder: tmpDir,
                size: "640x?",
              })
              .on("end", () => resolve())
              .on("error", (err: unknown) => reject(err));
          });

          const frameBuf = await fs.readFile(snapshotFile);
          const thumbName = storagePath.replace(/(\.\w+)$/, "-thumb.jpg");
          await StorageService.uploadBuffer(thumbName, frameBuf, "image/jpeg");
          thumbnailPath = thumbName;
          thumbnailUrl = await StorageService.generateSignedUrl(thumbName, 3600);

          // cleanup tmp files
          await fs.unlink(tmpFile).catch(() => {});
          await fs.unlink(snapshotFile).catch(() => {});
        } catch (err) {
          logger.warn("Video thumbnail generation failed, continuing without thumbnail", err);
        }
      }
    } catch (err) {
      logger.warn("Thumbnail generation error", err);
    }

    const createdAt = new Date().toISOString();

    // Create memory doc in event subcollection (flat schema)
    const memoryDoc = await FirestoreService.createSubcollectionDocument(
      COLLECTIONS.EVENTS,
      eventId,
      COLLECTIONS.MEMORIES,
      {
        eventId,
        uploaderId: data.createdBy || null,
        mediaUrl: null, // we will generate signed url below for response
        storagePath,
        mediaType: fileInfo.mediaType === "image" ? "photo" : fileInfo.mediaType === "video" ? "video" : "other",
        thumbnailUrl,
        caption: data.title || data.description || fileInfo.originalName || null,
        tags: data.tags || [],
        visibility: data.visibility || "guests",
        uploadedAt: createdAt,
        updatedAt: createdAt,
        size: fileInfo.size || 0,
        contentType: fileInfo.mimetype,
        mediaId: null,
      }
    );

    // Create top-level media index document
    const mediaIndex = await FirestoreService.createDocument(COLLECTIONS.MEDIA, {
      eventId,
      memoryId: memoryDoc.id,
      storagePath,
      thumbnailPath,
      uploadedAt: createdAt,
    });

    // Attach mediaId and generate signed URLs
    await FirestoreService.updateSubcollectionDocument(COLLECTIONS.EVENTS, eventId, COLLECTIONS.MEMORIES, memoryDoc.id, {
      mediaId: mediaIndex.id,
      updatedAt: new Date().toISOString(),
    });

    const mediaUrl = await StorageService.generateSignedUrl(storagePath, 3600);
    const thumbUrl = thumbnailPath ? await StorageService.generateSignedUrl(thumbnailPath, 3600) : null;

    // Return enriched response
    return {
      ...memoryDoc,
      mediaId: mediaIndex.id,
      storagePath,
      mediaUrl,
      thumbnailUrl: thumbUrl,
    };
  }

  static async updateMemory(eventId: string, memoryId: string, data: Partial<MemoryInput>): Promise<any> {
    await FirestoreService.updateSubcollectionDocument(
      COLLECTIONS.EVENTS,
      eventId,
      COLLECTIONS.MEMORIES,
      memoryId,
      {
        ...data,
        updatedAt: new Date().toISOString(),
      }
    );

    logger.info("Memory updated", {eventId, memoryId});
    return this.getMemory(eventId, memoryId);
  }

  static async deleteMemory(eventId: string, memoryId: string): Promise<void> {
    const memory = await this.getMemory(eventId, memoryId);

    if (memory?.storagePath) {
      try {
        await StorageService.deleteFile(memory.storagePath);
      } catch (err) {
        logger.warn("Failed deleting storage file", err);
      }
    }

    if (memory?.thumbnailPath) {
      try {
        await StorageService.deleteFile(memory.thumbnailPath);
      } catch (err) {
        logger.warn("Failed deleting thumbnail", err);
      }
    }

    if (memory?.mediaId) {
      try {
        await FirestoreService.deleteDocument(COLLECTIONS.MEDIA, memory.mediaId);
      } catch (err) {
        logger.warn("Failed deleting media index", err);
      }
    }

    await FirestoreService.deleteSubcollectionDocument(COLLECTIONS.EVENTS, eventId, COLLECTIONS.MEMORIES, memoryId);
    logger.info("Memory deleted", {eventId, memoryId});
  }
}
